### ISSUE TITLE
Failed to unpack GroupKeyEnvelope because magic identifier is empty

### ISSUE THREAD

**Issue by schorschii** [jborean93/dpapi-ng#2]
Hi,
First of all, thanks for your great work!

I'm trying to decrypt a LAPS password (`msLAPS-EncryptedPassword`) and I get the following error:
```
Traceback (most recent call last):
  File "/media/georg/Data2/Sourcecode/Linux/laps4linux/./laps-gui.py", line 502, in queryAttributes
    decrypted = dpapi_ng.ncrypt_unprotect_secret(
  File "/home/georg/.local/lib/python3.10/site-packages/dpapi_ng/_client.py", line 495, in ncrypt_unprotect_secret
    rk = _sync_get_key(
  File "/home/georg/.local/lib/python3.10/site-packages/dpapi_ng/_client.py", line 203, in _sync_get_key
    return _process_get_key_result(resp)
  File "/home/georg/.local/lib/python3.10/site-packages/dpapi_ng/_client.py", line 119, in _process_get_key_result
    return GetKey.unpack_response(raw_resp)
  File "/home/georg/.local/lib/python3.10/site-packages/dpapi_ng/_gkdi.py", line 137, in unpack_response
    return GroupKeyEnvelope.unpack(view[16 : 16 + key_length])
  File "/home/georg/.local/lib/python3.10/site-packages/dpapi_ng/_gkdi.py", line 540, in unpack
    raise ValueError(f"Failed to unpack {cls.__name__} as magic identifier {view[4:8].tobytes()} is invalid")
ValueError: Failed to unpack GroupKeyEnvelope as magic identifier b'' is invalid
```
I can see that the `view` object does not contain any bytes.

The issue seems to be in `_process_get_key_result()` (`_client.py` line 112):
`raw_resp` is empty after cutting the padding with `response.stub_data[:-pad_length]`. When using `response.stub_data` directly, the decryption works without any issues.

Additional context for reproducing:
After retrieving the `msLAPS-EncryptedPassword` with the ldap3 library, I'm cutting the first 16 bytes before passing the data to your library (without that, the following error will be thrown: `dpapi_ng._asn1.NotEnougData: Not enough data: expecting 61082037254736105 but got 1264`).
```
decrypted = dpapi_ng.ncrypt_unprotect_secret(
	ldap_raw_value[16:],
	server = 'x.x.x.x',
	username = 'administrator@domain.tld',
	password = 'xxx'
)
```

**Comment by jborean93** [comment]
Thanks for the information, I'll have the play around with it a bit more as this should work. I wonder if your RPC server is configured to only encrypt the payload but not sign the headers causing some values to be unpacked differently. I'll have to play around with it a bit more.

Can you share what Windows version your domain controller is. It'll be good to try and replicate it.

**Comment by jborean93** [comment]
Actually I think I see the issue, your payload has no padding so it's doing `response.stub_data[:-0]` which is trimming the whole thing. I'll have to update the logic to correctly handle the no padding scenario.

**Comment by schorschii** [comment]
Thanks. I'm using a fresh installed Windows Server 2022 and a Windows 10 22H2 client with the latest updates.

Btw. I'm trying to implement encryption in [this branch](https://github.com/schorschii/dpapi-ng/tree/encryption). I think it could work but a `pack()` function for the DPAPINGBlob object to bytes is still missing. I'll continue throughout the week.

**Comment by jborean93** [comment]
Nice excited to see the encryption side, would be great to do both outside of Windows. I didn't bother with the `pack()` function for the blob as it would have been a bit more work for the initial MVP. Let me know if you need any help with it.

**Comment by jborean93** [comment]
The PR should hopefully fix your issue https://github.com/jborean93/dpapi-ng/pull/3.
