### ISSUE TITLE
Question regarding ECDH_P521 root key creation on Windows Server 2022

### ISSUE THREAD

**Issue by schorschii** [jborean93/dpapi-ng#5]
While working on the encryption part, I also tried to use ECDH_P521. Steps are the same as when generating ECDH_P256 and ECDH_P384 root key on the server:

1. Set group key distribution service parameters in ADSI editor: `CN=Group Key Distribution Service Server Configuration,CN=Server Configuration,CN=Group Key Distribution Service,CN=Services,CN=Configuration,DC=DOMAIN,DC=TLD`
   ```
   msKds-KDFAlgorithmID = SP800_108_CTR_HMAC
   msKds-SecretAgreementAlgorithmID = ECDH_P521
   msKds-PrivateKeyLength = 521
   msKds-PublicKeyLength = 521
   msKds-KDFParam = 00 00 00 00 01 00 00 00 0E 00 00 00 00 00 00 00 53 00 48 00 41 00 35 00 31 00 32 00 00 00  (SHA512)
   ```
3. Execute `Add-KdsRootKey`

But instead of success as when using ECDH_P256 and ECDH_P384, on ECDH_P521 I get the following error:
```
Add-KdsRootKey : Ausnahme von HRESULT: 0xD000000D
In Zeile:1 Zeichen:1
+ Add-KdsRootKey
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-KdsRootKey], COMException
    + FullyQualifiedErrorId : Ausnahme von HRESULT: 0xD000000D,Microsoft.KeyDistributionService.Cmdlets.AddKdsRootKeyC
   ommand
```

Is this what you mean with "a test environment cannot be created with it" in your README.md? Seems to be a bug in windows server, isn't it?

**Comment by jborean93** [comment]
That's exactly what I mean, I couldn't configure it at all so I couldn't test it out. I used https://github.com/jborean93/dpapi-ng/blob/main/tests/integration/files/New-KdsRootKey.ps1 as my script to configure the keys and while ECDH_P256 and ECDH_P384 worked just fine, ECDH_P521 failed with the same error you see.

**Comment by schorschii** [comment]
OK, this really seems to be a Windows bug. As soon as `msKds-PrivateKeyLength` or `msKds-PublicKeyLength` is set to a value greater than 512, which is necessary for ECDH_P521, it will throw HRESULT `0xD000000D`. If you set it to something below or equal to 512, it will correctly throw `Invalid SecretAgreementPublicKeyLength` or `Invalid SecretAgreementPrivateKeyLength` for ECDH_P521.

I tried this with different Windows Server versions and editions (Standard and Datacenter), always the same.

**Comment by jborean93** [comment]
Yea for now I just gave up on testing it, even online I haven't seen any evidence of anyone even changing the keys from DH to one of the ECDH_P* algorithms. If someone ends up figuring it out (or MS fixes the bug) then I'll update the test suite but for now it'll just go untested.
