### ISSUE TITLE
cryptography >= 3.1 is required

### ISSUE THREAD

**Issue by rkerr** [jborean93/dpapi-ng#9]
The README doesn't specify a minimum version for cryptography but trying to use dpapi-ng on an ubuntu 20.04 box with cryptography 2.8 results in the error:

> missing 1 required positional argument: 'backend'

From the release notes it seems cryptography 3.1 is the first version to make the 'backend' argument optional.

It would be good if the requirements could be updated.

**Comment by jborean93** [comment]
I can certainly update the requirements to reflect this but keep in mind 2.8 is from 2019 which is 5 years old at this point in time. I appreciate you sharing this though as the min should definitely be valid for what it needs.

**Comment by jborean93** [comment]
I've set the minimum in https://github.com/jborean93/dpapi-ng/pull/10. I chose 3.4.4 due to type annotations which isn't really a runtime requirement but it helped simplify testing requirements.

**Comment by rkerr** [comment]
Appreciate it's a pretty old version - ran into the issue as Ubuntu 20.04 LTS ships 2.8 and is still in support for a few months (and of course for some people there are paid support options that may leave it running longer).
